[package]
name = "rust_template"
version = "0.1.0"
edition = "2021"
authors = ["crrow"]
license = "Apache-2.0"
description = "A template for rust projects"
homepage = "https://github.com/crrow/rsketch"
repository = "https://github.com/crrow/rsketch"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[example]]
name = "hello-world"
path = "examples/hello_world.rs"

[workspace]
resolver = "2"
members = ["src/common"]

exclude = [
    "target", # exclude bench testing
]

[workspace.dependencies]
snafu = "0.8.2"
tokio = { version = "1.35.1", features = ["full", "tracing"] }
tracing = "0.1.40"
serde = "1.0.197"