name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  # tells the Rust compiler to emit additional warnings during compilation that it might not normally report by default.
  RUSTFLAGS: -Dwarnings
  # used for debugging purposes.
  RUST_BACKTRACE: 1
  rust_stable: stable
  rust_nightly: nightly-2024-01-23
  rust_clippy: '1.77'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  basics:
    name: basic checks
    runs-on: ubuntu-latest
    needs:
      - clippy
      - fmt
      - docs
    steps:
      - run: exit 0
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.rust_clippy }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_clippy }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: "clippy --all"
        run: cargo clippy --all --tests --all-features --no-deps
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.rust_nightly }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_nightly }}
      - name: "doc --lib --all-features"
        run: cargo doc --lib --no-deps --all-features --document-private-items
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run fmt
        run: cargo +nightly fmt --all -- --check --unstable-features