name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  check:
    name: cargo check
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check

  fmt:
    name: format rust code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check